name: Run Flask Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest

    services:
      flask-app:
        image: tiangolo/uwsgi-nginx-flask:python3.8
        ports:
          - 5000:5000
        env:
          FLASK_ENV: development
        options: >-
          --entrypoint=""
        volumes:
          - .:/app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask App
        run: |
          flask run --host=0.0.0.0 &
          echo $! > flask.pid 
          sleep 5 

      - name: Run test
        run: python -m unittest discover -s tests -p "test_app.py"

      - name: Stop Flask App
        run: |
          kill $(cat flask.pid)
