name: Run Flask Tests & CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest

    services:
      flask-app:
        image: tiangolo/uwsgi-nginx-flask:python3.8
        ports:
          - 5000:5000
        env:
          FLASK_ENV: development
        volumes:
          - .:/app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flask App
        run: |
          flask run --host=0.0.0.0 &
          sleep 5 

      - name: Run Selenium tests
        run: |
          python -m unittest discover -s tests

      - name: Stop Flask
        run: |
          kill $(lsof -t -i:5000)


  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy to App Engine
        run: |
          gcloud app deploy --quiet


